name    'lex-newrelic_plugin_agent'
version '1.0.0'
dependency 'puppetlabs/concat', '>= 1.0.2'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'puppetlabs/python', '>= 1.0.0'
source 'git://github.com/rlex/puppet-newrelic_plugin_agent.git'
author 'Lex Rivera <me@lex.io>'
license 'Creative Commons Attribution 3.0 Unported License'
summary 'Puppet newrelic-plugin-agent module'
description 'A module to deploy and manage the newrelic plugin agent server'
project_page 'https://github.com/rlex/puppet-newrelic_plugin_agent'
